Revert "fs/ntfs3: add a subset of W=1 warnings for stricter checks"
This reverts commit e33ae25f06eaab3543bc3f1c4acbb9b4f2b643de.

In file included from fs/ntfs3/index.c:14:
fs/ntfs3/index.c: In function ‘indx_delete_entry’:
fs/ntfs3/ntfs.h:716:13: error: ‘ib’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  716 |         u32 used = le32_to_cpu(hdr->used);
      |             ^~~~
fs/ntfs3/index.c:2285:30: note: ‘ib’ was declared here
 2285 |         struct INDEX_BUFFER *ib;
      |                              ^~
cc1: all warnings being treated as errors
  CC      arch/x86/kernel/rtc.o
make[7]: *** [scripts/Makefile.build:287: fs/ntfs3/index.o] Error 1
make[6]: *** [scripts/Makefile.build:544: fs/ntfs3] Error 2
make[5]: *** [scripts/Makefile.build:544: fs] Error 2
make[5]: *** Waiting for unfinished jobs....